services:

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile

    container_name: aufildessaisons_php

    volumes:
      - .:/var/www/html

    ports:
      - "8000:8000"

    depends_on:
      - database

  database:
    image: mysql:8.4

    container_name: aufildessaisons_mysql

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aufildessaisons
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer

    container_name: aufildessaisons_adminer

    restart: always

    depends_on:
      - database

    ports:
      - "8080:8080"

volumes:
  mysql_data: